from typing import Optional, Protocol


class TokenStore(Protocol):
    def get_access_token(self) -> Optional[str]: ...
    def get_refresh_token(self) -> Optional[str]: ...
    def get_expiry(self) -> float: ...
    def save_tokens(self, tokens: dict) -> None: ...


class OAuthClient(Protocol):
    def exchange_code_for_token(self, auth_code: str) -> Optional[dict]: ...
    def refresh_access_token(self, refresh_token: str) -> Optional[dict]: ...


class BrowserLauncher(Protocol):
    def open(self, url: str) -> None: ...
